# Welcome to Jekyll!
#
# Site settings

title: Strive
email: 352683081@qq.com
avatar: https://avatars3.githubusercontent.com/u/34188429?s=460&u=9c8ebb94dc58a496aec50f6b560c25831875bbe9&v=4 #头像
description: >- # this means to ignore newlines until "baseurl:"
    走向测试开发❤️
url: "https://wangxiaoxi.cn" # the base hostname & protocol for your site, e.g. http://example.com
github_username: wangxiaoxi3
highlighter: rouge
svg:
  optimize: true
# Build settings
# theme: minima
highlighter-theme: monokai
date_format: "%Y-%M-%D"
plugins:
  - jekyll-feed
category_dir: category/
tag_dir: tag/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
